import os

class Config(object):
    SECRET_KEY = 'you-will-never-guess'
    ELASTICSEARCH_ADDR = os.environ['DOKKU_ELASTICSEARCH_POC_RECHERCHE_INDEX_PORT_9200_TCP_ADDR']
    ELASTICSEARCH_PORT = os.environ['DOKKU_ELASTICSEARCH_POC_RECHERCHE_INDEX_PORT_9200_TCP_PORT']
    ELASTICSEARCH_URL = f'http://{ELASTICSEARCH_ADDR}:{ELASTICSEARCH_PORT}'
